name: safezonemarketplace
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Firebase & Authentication
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  google_sign_in: ^6.1.0
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  firebase_database: ^12.1.0
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^19.5.0
  shared_preferences: ^2.5.4
  image_picker: ^1.2.1
  provider: ^6.1.5+1
  cached_network_image: ^3.4.1
  loading_animation_widget: ^1.3.0
  latlong2: ^0.9.1
  flutter_map: ^8.2.2
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  flutter_image_compress: ^2.4.0
  timeago: ^3.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
